version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microservice_db
      MYSQL_USER: account
      MYSQL_PASSWORD: account
    volumes:
      - db-data:/var/lib/mysql
    


volumes:
  db-data:
    