version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microservice_db
      MYSQL_USER: account
      MYSQL_PASSWORD: account
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - my-network

  account-microservice:
    build:
      context: ./account-microservice
    container_name: account-microservice-container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/microservice_db
      - SPRING_DATASOURCE_USERNAME=account
      - SPRING_DATASOURCE_PASSWORD=account
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - my-network

  client-microservice:
    build:
      context: ./client-microservice
    container_name: client-microservice-container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/microservice_db
      - SPRING_DATASOURCE_USERNAME=account
      - SPRING_DATASOURCE_PASSWORD=account
    ports:
      - "8082:8082"
    depends_on:
      - db
    networks:
      - my-network
networks:
  my-network:
    driver: bridge

volumes:
  db-data:
    