# Usar una imagen base de OpenJDK
FROM openjdk:17-jdk-slim

# Establecer el directorio de trabajo
VOLUME /tmp

ARG JAR_FILE= target/movimientos-0.0.1-SNAPSHOT.jar
# Copiar el archivo JAR de la aplicación al contenedor
ADD ${JAR_FILE} account-microservice.jar
#COPY  account-microservice.jar

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "account-microservice.jar"]